// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZFEYYsp_TCtEUGus8KRQ-E50q7SA0U9U',
    appId: '1:271206638945:web:575dda09d5277088ddd120',
    messagingSenderId: '271206638945',
    projectId: 'homework4-4d06a',
    authDomain: 'homework4-4d06a.firebaseapp.com',
    storageBucket: 'homework4-4d06a.firebasestorage.app',
    measurementId: 'G-K6VKLRL349',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7yzyTR7wq6zmpkw2oyqsa0R-N-6cCg6g',
    appId: '1:271206638945:android:0b7df266daab2e77ddd120',
    messagingSenderId: '271206638945',
    projectId: 'homework4-4d06a',
    storageBucket: 'homework4-4d06a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvkkX1v_OyWwbKtXBXVBJmVF24Q_97GQ0',
    appId: '1:271206638945:ios:799ef56f21ec1d26ddd120',
    messagingSenderId: '271206638945',
    projectId: 'homework4-4d06a',
    storageBucket: 'homework4-4d06a.firebasestorage.app',
    iosBundleId: 'com.example.homework4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvkkX1v_OyWwbKtXBXVBJmVF24Q_97GQ0',
    appId: '1:271206638945:ios:799ef56f21ec1d26ddd120',
    messagingSenderId: '271206638945',
    projectId: 'homework4-4d06a',
    storageBucket: 'homework4-4d06a.firebasestorage.app',
    iosBundleId: 'com.example.homework4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZFEYYsp_TCtEUGus8KRQ-E50q7SA0U9U',
    appId: '1:271206638945:web:d24cf634fd3f2b80ddd120',
    messagingSenderId: '271206638945',
    projectId: 'homework4-4d06a',
    authDomain: 'homework4-4d06a.firebaseapp.com',
    storageBucket: 'homework4-4d06a.firebasestorage.app',
    measurementId: 'G-NP7ZR77WZK',
  );
}
